# Generated by Django 2.1.5 on 2019-02-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blogimage',
            field=models.ImageField(default='default.jpg', upload_to='mainsite_pics'),
        ),
        migrations.AddField(
            model_name='portfoliopost',
            name='Port_image',
            field=models.ImageField(default='default.jpg', upload_to='mainsite_pics'),
        ),
    ]
